name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt-get install build-essential
        gcc $GITHUB_WORKSPACE/readability.c -o output -lm
        ./output
        gcc $GITHUB_WORKSPACE/scrabble.c -o output -lm
        ./output
        rm output
      

