name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt-get install build-essential
        echo $GITHUB_WORKSPACE
        gcc $GITHUB_WORKSPACE/readability.c -o output
        ./output
        rm output
      

