name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
      sudo apt-get install build-essential
      gcc ${{GITHUB_WORKSPACE}}${{GITHUB_EVENT_PATH}} -O output
      ./output
      rm output

