name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        sudo apt-get install build-essential
        
        gcc $GITHUB_WORKSPACE/CS50/week_2/problem_sets/readability.c -o output -lm
        ./output
        gcc $GITHUB_WORKSPACE/CS50/week_2/labs/scrabble.c -o output -lm
        ./output

        gcc $GITHUB_WORKSPACE/DSA/bubble_sort.c -o output -lm
        ./output
        gcc $GITHUB_WORKSPACE/DSA/selection_sort.c -o output -lm
        ./output
        gcc $GITHUB_WORKSPACE/DSA/linear_search.c -o output -lm
        ./output
        gcc $GITHUB_WORKSPACE/DSA/binary_search.c -o output -lm
        ./output
        rm output
        
        gcc $GITHUB_WORKSPACE/Project_Euler/1_sum_of_mult_two_nums.c -o output -lm
        ./output
        gcc $GITHUB_WORKSPACE/Project_Euler/2_even_fib_nums.c -o output -lm
        ./output
        gcc $GITHUB_WORKSPACE/Project_Euler/3_largest_prime_factor.c -o output -lm
        ./output
        gcc $GITHUB_WORKSPACE/Project_Euler/4_largest_palindrome_product.c -o output -lm
        ./output
        gcc $GITHUB_WORKSPACE/Project_Euler/5_smallest_multiple.c -o output -lm
        ./output
        gcc $GITHUB_WORKSPACE/Project_Euler/6_sum_square_diff.c -o output -lm
        ./output
        gcc $GITHUB_WORKSPACE/Project_Euler/7_nth_prime_number.c -o output -lm
        ./output
        gcc $GITHUB_WORKSPACE/Project_Euler/8_largest_product_in_a_series.c -o output -lm
        ./output

        rm output
      

